const quotes = [
  "Be better than you were yesterday.",
  "Don't waste time. You don't get it back.",
  "Focus.",
  "Permanently delete your social media accounts and uninstall those apps — success starts when distractions end.",
  "You have 86,400 seconds each day — start using them like your life depends on it, because it does.",
  "The problem is, you think you have a lot of time to live.",
  "Live everyday like it's your last day.",
  "Consistency.",
  "Big dreams need big sacrifices.",
  "Practice makes perfect.",
  "Do it even when you don't feel like it.",
  "Nothing changes if nothing changes.",
  "This is the way.",
  "Whatever it takes.",
  "Whether you think you can or you think you can't, you're right.",
  "Stay different.",
  "Excuses don't build empires.",
  "Stop overthinking. Start doing.",
  "Become addicted to constant improvement.",
  "Don't stop when you're tired. Stop when you're done.",
  "Great things never come from comfort zones.",
  "Your future is created by what you do today.",
  "Make yourself proud.",
  "One day or day one. You decide.",
  "Turn I wish into I will.",
  "Dream big. Work hard. Stay focused.",
  "Level up in silence.",
  "Every pro was once a beginner.",
  "Wake up with determination. Go to bed with satisfaction.",
  "Become the hardest worker in the room.",
  "Stay patient and trust your journey.",
  "If it was easy, everyone would do it.",
  "If you want it, work for it.",
  "Keep going. You’re getting there."
];

const q=document.getElementById("quote-text"),i=document.getElementById("instruction-prompt");let idx=-1,typing=false,timer=null,text="",chars=0,instShown=false;const DELAY=55,START=300;function align(t){q.classList.toggle("text-left",t.length>=35);q.classList.toggle("text-center",t.length<35)}function type(){typing=true;chars++;q.innerHTML=text.slice(0,chars)+'<span class="typing-cursor"></span>';if(chars>=text.length){typing=false;q.innerHTML=text;if(!instShown){instShown=true;setTimeout(()=>i.style.opacity="1",300)}return}timer=setTimeout(type,DELAY)}function start(t){if(timer)clearTimeout(timer);text=t;chars=0;align(t);q.style.opacity="0";setTimeout(()=>{q.style.opacity="1";type()},START)}function next(){idx=(idx+1)%quotes.length;start(quotes[idx]);if(instShown)i.style.opacity="0"}function click(){if(typing){clearTimeout(timer);typing=false;chars=text.length;q.innerHTML=text;if(!instShown){instShown=true;setTimeout(()=>i.style.opacity="1",300)}}else next()}document.addEventListener("DOMContentLoaded",()=>{q.style.opacity="1";next()});document.body.onclick=click;
